name: smartpay
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts:
  stacked: ^3.4.2
  line_icons: ^2.0.1
  shared_preferences: ^2.0.15
  flutter_svg:
  http: ^0.13.5
  page_transition: ^2.0.9
  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.0.12
  go_router: ^6.0.9
  websafe_svg: ^2.1.2
  dropdown_search: ^5.0.6
  file_picker: ^5.2.10
  flutter_native_splash: ^2.2.18
  share_plus: ^6.3.4
  image_gallery_saver: ^2.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/smartpay_logo_splash.png
  color_dark: "#121212"
  image_dark: assets/smartpay_logo_splash.png

  android_12:
    # image: assets/smartpay_logo_splashpng
    icon_background_color: "#ffffff"
    # image_dark: assets/smartpay_logo_splash.png
    icon_background_color_dark: "#121212"

  web: true

flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/avatar/
    - assets/cards/
    - assets/screenshots/