// //General services
// export '../../services/general/biometrics.dart';
// export '../../services/general/setTransactionPin.dart';
// export '../../services/notification/notificationSocket.dart';
// export 'package:pcash/services/general/transactionType.dart';
// export 'package:pcash/services/general/paymentMethod.dart';
// export 'package:pcash/services/general/reportTransaction.dart';
// export 'package:pcash/services/general/getAllNotifications.dart';
// export 'package:pcash/services/general/clearAllNotifications.dart';
// export 'package:pcash/services/general/readNotification.dart';
// export 'package:pcash/services/general/confirmCard.dart';
// export 'package:pcash/services/general/telegramRequest.dart';
// export 'package:pcash/services/general/updateCheck.dart';
// export 'package:pcash/services/general/payStackKeys.dart';
// export 'package:pcash/services/general/promoPopUp.dart';
// export 'package:pcash/services/general/promoWriteUp.dart';

// //Authentication services
// export '../../services/authentication/createAccount.dart';
// export '../../services/authentication/login.dart';
// export '../../services/authentication/biometricLogin.dart';
// export '../../services/authentication/sendOtp.dart';
// export '../../services/authentication/setPassword.dart';
// export '../../services/authentication/verifyOtp.dart';
// export '../../services/authentication/uploadProfilePicture.dart';
// export '../../services/authentication/getCountries.dart';
// export '../../services/authentication/getStates.dart';
// export '../../services/authentication/getCities.dart';
// export '../../services/authentication/getAllSecurityQuestions.dart';
// export '../../services/authentication/setSecurityAnswer.dart';
// export '../../services/authentication/getSecurityQuestion.dart';
// export '../../services/authentication/confirmSecurityAnswer.dart';
// export '../../services/authentication/resetPassword.dart';
// export '../../services/authentication/verifyEmail.dart';
// export '../../services/authentication/verifyPhoneNumber.dart';
// export '../../services/authentication/detectFace.dart';
// export '../../services/authentication/utilityBill.dart';
// export '../../services/authentication/sendEmailOtp.dart';
// export '../../services/authentication/verifyEmailOtp.dart';
